# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod 'Google/Analytics'
pod 'Google-Mobile-Ads-SDK'

target 'FlickIt' do

end

target 'FlickItTests' do

end

target 'FlickItUITests' do

end

